name: openrsd
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.7.22=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.1.0=he5830b7_0
  - libgomp=13.1.0=he5830b7_0
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.42.0=h2797004_0
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4=hcb278e6_0
  - openssl=3.1.1=hd590300_1
  - pip=23.2.1=pyhd8ed1ab_0
  - python=3.8.17=he550d4f_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=68.0.0=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - wheel=0.41.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
    - absl-py==1.4.0
    - accelerate==0.22.0
    - adapter-transformers==3.2.1
    - addict==2.4.0
    - aiohttp==3.8.6
    - aiosignal==1.3.1
    - albumentations==1.3.1
    - asttokens==2.4.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - braceexpand==0.1.7
    - bypy==1.8.9
    - cachetools==5.3.1
    - certifi==2023.7.22
    - charset-normalizer==3.2.0
    - click==8.1.6
    - clip==1.0
    - clip-benchmark==1.6.1
    - colorama==0.4.6
    - contourpy==1.1.0
    - cycler==0.11.0
    - cython==3.0.8
    - dill==0.3.7
    - dotadevkit==1.3.0
    - e2cnn==0.2.3
    - einops==0.6.1
    - einx==0.2.2
    - et-xmlfile==1.1.0
    - executing==2.0.1
    - facexlib==0.3.0
    - faiss-gpu==1.7.2
    - filelock==3.12.2
    - filterpy==1.4.5
    - fire==0.6.0
    - fonttools==4.41.1
    - frozendict==2.4.4
    - frozenlist==1.4.0
    - fsspec==2023.6.0
    - ftfy==6.2.0
    - future==1.0.0
    - google-auth==2.23.0
    - google-auth-oauthlib==1.0.0
    - grpcio==1.58.0
    - h5py==3.11.0
    - huggingface-hub==0.24.5
    - icecream==2.1.3
    - idna==3.4
    - imagecodecs==2023.3.16
    - imageio==2.31.1
    - imgaug==0.4.0
    - importlib-metadata==6.8.0
    - importlib-resources==6.0.0
    - joblib==1.3.2
    - kiwisolver==1.4.4
    - lazy-loader==0.3
    - lightning-utilities==0.9.0
    - llvmlite==0.41.1
    - lmdb==1.5.1
    - markdown==3.4.4
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - mat4py==0.6.0
    - matplotlib==3.7.2
    - mdurl==0.1.2
    - mmcv==2.1.0
    - model-index==0.1.11
    - mpmath==1.3.0
    - multidict==6.0.4
    - multiprocess==0.70.15
    - networkx==3.1
    - numba==0.58.1
    - numpy==1.24.4
    - oauthlib==3.2.2
    - open-clip-torch==2.24.0
    - openai-clip==1.0.1
    - opencv-contrib-python==4.9.0.80
    - opencv-python==4.8.0.74
    - opencv-python-headless==4.8.0.76
    - opendatalab==0.0.9
    - openmim==0.3.9
    - openpyxl==3.1.2
    - ordered-set==4.1.0
    - packaging==23.1
    - pandas==2.0.3
    - pillow==10.0.0
    - platformdirs==3.10.0
    - prettytable==3.8.0
    - protobuf==4.24.3
    - psutil==5.9.5
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pybboxes==0.1.6
    - pyclustering==0.10.1.2
    - pycocoevalcap==1.2
    - pycocotools==2.0.6
    - pycryptodome==3.18.0
    - pygments==2.15.1
    - pyiqa==0.1.11
    - pynvml==11.5.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytorch-lightning==2.1.0
    - pytz==2023.3
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - qudida==0.0.4
    - regex==2023.8.8
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - requests-toolbelt==1.0.0
    - rich==13.5.0
    - rsa==4.9
    - safetensors==0.4.3
    - sahi==0.11.18
    - scikit-image==0.21.0
    - scikit-learn==1.3.0
    - scipy==1.10.1
    - seaborn==0.13.2
    - sentencepiece==0.2.0
    - shapely==2.0.1
    - six==1.16.0
    - sympy==1.12
    - tabulate==0.9.0
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.1
    - termcolor==2.3.0
    - terminaltables==3.1.10
    - threadpoolctl==3.2.0
    - tifffile==2023.7.10
    - timm==0.9.2
    - tokenizers==0.15.2
    - toml==0.10.2
    - tomli==2.0.1
    - torch==1.12.1+cu102
    - torch-rs==0.0.4
    - torchaudio==0.12.1+cu102
    - torchmetrics==1.2.0
    - torchvision==0.13.1+cu102
    - tqdm==4.65.0
    - transformers==4.37.2
    - typing-extensions==4.7.1
    - tzdata==2023.3
    - urllib3==1.26.16
    - wcwidth==0.2.13
    - webdataset==0.2.86
    - werkzeug==2.3.7
    - xformer==1.0.1
    - yapf==0.40.1
    - yarl==1.9.2
    - zipp==3.16.2
prefix: /home/huangziyue/data/anaconda3/envs/openrsd
